---
# tasks file for ansible-apt-mirror
- include: debian.yml
  when:
    - ansible_os_family == "Debian"
    - apt_mirror_client is defined
    - not apt_mirror_client|bool

- include: config_apt_mirror.yml
  when:
    - ansible_os_family == "Debian"
    - apt_mirror_client is defined
    - not apt_mirror_client|bool

- include: config_apt_mirror_client.yml
  when:
    - ansible_os_family == "Debian"
    - apt_mirror_client is defined
    - apt_mirror_client|bool

- include: config_apt_mirror_schedule.yml
  when:
    - ansible_os_family == "Debian"
    - apt_mirror_client is defined
    - not apt_mirror_client|bool
    - apt_mirror_schedule_updates is defined
    - apt_mirror_schedule_updates|bool

- include: config_apache2_symlinks.yml
  when:
    - ansible_os_family == "Debian"
    - apt_mirror_client is defined
    - not apt_mirror_client|bool
    - apt_mirror_schedule_updates is defined
    - apt_mirror_schedule_updates|bool

- include: get_gpg.yml
  when:
    - kuboardspray_get_gpg is defined
    - kuboardspray_get_gpg|bool